/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-118305-g8eb1d76e14-20250114"
#endif /* AVUTIL_FFVERSION_H */
